## Deploy verticles to WildFly server

With this extension integrated, you can deploy the Vert.x verticle implementation to the WildFly server by specifying a deployment descriptor.

The availability of the deployment descriptor activates a `DeploymentUnitProcessor` to check the existing Vert.x instances inside the WildFly server, and select the one specified in the deployment descriptor.

A typical war deployment structure which contains a verticle implementation is:

.WAR deployment with verticle implementation
[source, bash]
----
test-verticle.war:
/WEB-INF/
/WEB-INF/vertx-deployment.json
/WEB-INF/classes/
/WEB-INF/classes/org/
/WEB-INF/classes/org/wildfly/
/WEB-INF/classes/org/wildfly/extension/
/WEB-INF/classes/org/wildfly/extension/vertx/
/WEB-INF/classes/org/wildfly/extension/vertx/test/
/WEB-INF/classes/org/wildfly/extension/vertx/test/mini/
/WEB-INF/classes/org/wildfly/extension/vertx/test/mini/deployment/
/WEB-INF/classes/org/wildfly/extension/vertx/test/mini/deployment/TestVerticle.class
----

The content of the deployment descriptor(`WEB-INF/vertx-deployment.json`) is:

.Deployment descriptor content
[source, json]
----
{
  "deployments": [
    {
      "verticle-class": "org.wildfly.extension.vertx.test.mini.deployment.TestVerticle",
      "vertx": "default"
    }
  ]
}
----

when it is deployed, the `TestVerticle` will be deployed to the Vert.x instance with name: `default` using the default `DeploymentOptions` too.

These deployed verticles inside the Vert.x instance will be un-deployed when the deployment gets un-deployed from WildFly server.

### Deployment Descriptor

The deployment descriptor to be able to deploy the verticle is either at `META-INF/vertx-deployment.json` or `WEB-INF/vertx-deployment.json`.

A full example of `vertx-deployment.json` is:

.Full example of vertx-deployment.json
[source, json]
----
{
  "ver": 1,
  "deployments": [
    {
      "verticle-class": "org.wildfly.extension.vertx.test.mini.deployment.TestVerticle",
      "vertx": "default",
      "deploy-options": {}
    }
  ]
}
----

* `ver`    -    The version of the deployment descriptor, it is `1`, and it can be skipped now.
* `deployments`    -    An array of the deployments, each of which is a json structure.
** `verticle-class`    -    The FQCN of the verticle class which will be deployed.
** `vertx`    -    The vertx name which the verticle should be deployed to.
*** Defaults to `default` if not specified.
** `deploy-options`    -    The `DeploymentOptions` which is used to do the deployment.
*** The format of the content matches what https://vertx.io/docs/apidocs/io/vertx/core/DeploymentOptions.html#DeploymentOptions-io.vertx.core.json.JsonObject-[new DeploymentOptions(JsonObject)] constructor requires.
*** Default `DeploymentOptions` is used if not specified.
*** The `ModuleClassLoader` of current deployment will be used for deploying the Verticle.

