## Vertx used in application

You can use the Vert.x instance in your applications.

Vert.x instance is the key to all Vert.x applications, each function and capability comes from the Vert.x instance, so having the Vert.x instance injected in the application codes is important.

This extension provides 2 ways to access the Vert.x instance.

### Access the Vert.x instance using JNDI lookup

you can access the Vert.x using the `@Resource(lookup = "java:/jboss/vertx/default")` annotation like:

.Access Vert.x using JNDI lookup
[source, java]
----
@WebServlet(value = "/async", asyncSupported = true)
public class AsyncServlet extends HttpServlet {

    @Resource(name = "java:/jboss/vertx/default")
    private Vertx vertx;

        @Override
    public void init() throws ServletException {
        vertx.eventBus()
                .<String>consumer("echo")
                .handler(msg -> msg.reply(msg.body()));
    }
}
----


### Access the Vert.x instance using CDI

The other way to use the Vert.x instance in the application is to use `@Inject Vertx vertx` annotation. When the CDI is activated(via a `beans.xml` file bundled in the deployment archive), the Vert.x instance will be injected.

.Access Vert.x instance using CDI
[source, java]
----
@Stateless
public class EchoService {
    @Inject
    private Vertx vertx;

    @Asynchronous
    public Future<String> echo(String message) {
        return (CompletableFuture<String>)vertx.eventBus()
                   .request("echo", message)
                   .map(msg -> msg.body().toString()).toCompletionStage();
    }

}
----
