name: CI Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        jdk: [11, 17]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.jdk }}
      - name: Run Build with -Prelease
        run: mvn -q clean install -Prelease -DtestLogToFile=false "-Djdk.io.File.enableADS=true"
