name: CI Tests
on:
  push:
    branches:
      - 1.x
  pull_request:
    branches:
      - 1.x
jobs:
  Test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        jdk: [17, 21]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.jdk }}
      - name: Run Build with -Prelease
        run: mvn -q clean install -fae -B -Prelease -DtestLogToFile=false "-Dextra.server.jvm.args=-Djdk.io.File.enableADS=true"
