name: Doc Site Generator
on:
  push:
    branches:
      - master
    paths:
      - docs/**
jobs:
  Build-Docs:
    name: Generate doc site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'
      - name: Run Build with -Prelease
        run: mvn -q clean install -Prelease -DskipTests
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/target/generated-docs
